if [ "$SSH_PUBLIC_KEYS_B64" = "" ]; then
    SSH_PUBLIC_KEYS_B64="$(cat $HOME/.ssh/id_rsa.pub | base64 -w0)"
fi

export TF_VAR_proxmox_host="$PROXMOX_HOST"
export TF_VAR_proxmox_token_id="$PROXMOX_TOKEN_ID"
export TF_VAR_proxmox_token_secret="$PROXMOX_TOKEN_SECRET"
export TF_VAR_proxmox_tls_insecure="$PROXMOX_TLS_INSECURE"
export TF_VAR_proxmox_node="$PROXMOX_NODE"
export TF_VAR_proxmox_parallel="$PROXMOX_PARALLEL"
export TF_VAR_proxmox_timeout="$PROXMOX_TIMEOUT"
export TF_VAR_internal_net_name="$INTERNAL_NET_NAME"
export TF_VAR_internal_net_subnet_cidr="$INTERNAL_NET_SUBNET_CIDR"
export TF_VAR_ssh_public_keys_b64="$SSH_PUBLIC_KEYS_B64"
export TF_VAR_vm_user="$VM_USER"
export TF_VAR_vm_sockets="$VM_SOCKETS"
export TF_VAR_vm_max_vcpus="$VM_MAX_VCPUS"
export TF_VAR_vm_cpu_type="$VM_CPU_TYPE"
export TF_VAR_vm_os_disk_storage="$VM_OS_DISK_STORAGE"
export TF_VAR_worker_node_data_disk_storage="$WORKER_NODE_DATA_DISK_STORAGE"
export TF_VAR_worker_node_data_disk_size="$WORKER_NODE_DATA_DISK_SIZE"
export TF_VAR_vm_clone="$VM_CLONE"
export TF_VAR_vm_count="$VM_COUNT"
export TF_VAR_vm_vcpus="$VM_VCPUS"
export TF_VAR_vm_memory="$VM_MEMORY"
export TF_VAR_vm_disk_size="$VM_DISK_SIZE"
