module "nodes" {
  source              = "./modules/proxmox_vm"
  node_count          = var.vm_count
  proxmox_node        = var.proxmox_node
  vm_clone            = var.vm_clone
  vm_name_prefix      = "vm-ceph"
  vm_max_vcpus        = var.vm_max_vcpus
  vm_vcpus            = var.vm_vcpus
  vm_sockets          = var.vm_sockets
  vm_cpu_type         = var.vm_cpu_type
  vm_memory_mb        = var.vm_memory
  vm_os_disk_storage  = var.vm_os_disk_storage
  vm_os_disk_size_gb  = var.vm_disk_size
  vm_net_name         = var.internal_net_name
  vm_net_subnet_cidr  = var.internal_net_subnet_cidr
  vm_user             = var.vm_user
  vm_tags             = "terraform;ceph"
  ssh_public_keys_b64 = var.ssh_public_keys_b64
}
