#!/bin/sh

set -e

. "$(dirname "$0")/../prompt.sh"
. "$(dirname "$0")/defaults.sh"

cat << 'EOF'
# Hetzner Cloud Configuration
# Generated by rock8s config tool
EOF

_TOKEN="$(prompt_password "Enter your Hetzner Cloud API token" "HETZNER_TOKEN")"
echo "export HETZNER_TOKEN=$_TOKEN"

_IMAGE="$(prompt_enum "Select server image" "SERVER_IMAGE" "$DEFAULT_IMAGE" $AVAILABLE_IMAGES)"
echo "export SERVER_IMAGE=$_IMAGE"

_LOCATION="$(prompt_enum "Select location" "LOCATION" "$DEFAULT_LOCATION" $AVAILABLE_LOCATIONS)"
echo "export LOCATION=$_LOCATION"

_NETWORK="$(prompt_text "Enter network name" "NETWORK_NAME" "$DEFAULT_NETWORK_NAME")"
echo "export NETWORK_NAME=$_NETWORK"

_MASTER_TYPE="$(prompt_enum "Select master node type" "" "$DEFAULT_SERVER_TYPE" $AVAILABLE_SERVER_TYPES)"
_MASTER_COUNT="$(prompt_text "Enter number of master nodes" "" "$DEFAULT_MASTER_COUNT")"
_MASTERS="${_MASTER_TYPE}:${_MASTER_COUNT}"
echo "export MASTERS=$_MASTERS"

_WORKER_TYPE="$(prompt_enum "Select worker node type" "" "$DEFAULT_SERVER_TYPE" $AVAILABLE_SERVER_TYPES)"
_WORKER_COUNT="$(prompt_text "Enter number of worker nodes" "" "$DEFAULT_WORKER_COUNT")"
_WORKERS="${_WORKER_TYPE}:${_WORKER_COUNT}"
echo "export WORKERS=$_WORKERS"

_USE_USER_DATA="$(prompt_boolean "Do you want to provide user-data script" "USER_DATA" "0")"
if [ "$_USE_USER_DATA" = "1" ]; then
    cat << 'EOF'
export USER_DATA="#cloud-config
package_update: true
package_upgrade: true
"
EOF
fi
