#!/bin/sh

AVAILABLE_IMAGES="debian-12 ubuntu-22.04 rocky-9"
AVAILABLE_LOCATIONS="nbg1 fsn1 hel1 ash dc1"
AVAILABLE_SERVER_TYPES="cx11 cx21 cx31 cx41 cx51 cpx11 cpx21 cpx31 cpx41 cpx51"

DEFAULT_IMAGE="debian-12"
DEFAULT_LOCATION="nbg1"
DEFAULT_MASTER_COUNT="1"
DEFAULT_NETWORK_NAME="private"
DEFAULT_SERVER_TYPE="cx21"
DEFAULT_WORKER_COUNT="2"

: "${LOCATION:=$DEFAULT_LOCATION}"
: "${NETWORK_NAME:=$DEFAULT_NETWORK_NAME}"
: "${SERVER_IMAGE:=$DEFAULT_IMAGE}"
