Vagrant.configure("2") do |config|
  config.vm.box = "pfsense-2.7.2"
  config.vm.boot_timeout = 900
  config.ssh.username = "root"
  config.ssh.password = "pfsense"
  config.ssh.insert_key = false
  config.vm.network :forwarded_port, guest: 443, host: 10443, auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 10080, auto_correct: true
  config.vm.provider 'libvirt' do |libvirt, override|
    libvirt.memory = 2048
    libvirt.cpus = 2
    override.vm.network "private_network",
      ip: "192.168.100.3",
      netmask: "255.255.255.0",
      :libvirt__network_name => "pfsense"
  end
  config.vm.provider 'virtualbox' do |vb, override|
    vb.memory = 2048
    vb.cpus = 2
    override.vm.network "private_network",
      ip: "192.168.56.8",
      netmask: "255.255.255.0",
      adapter: 2
  end
end
