VARS := -var cores=$(CORES) \
		-var cpu=$(CPU) \
		-var disk_format=$(DISK_FORMAT) \
		-var disk_size=$(DISK_SIZE) \
		-var iso_checksum=$(ISO_CHECKSUM) \
		-var iso_file=$(ISO_FILE) \
		-var iso_storage_pool=$(ISO_STORAGE_POOL) \
		-var iso_url=$(ISO_URL) \
		-var memory=$(MEMORY) \
		-var network_bridge=$(NETWORK_BRIDGE) \
		-var network_ip=$(NETWORK_IP)
