---
- name: Define haproxy regex patterns
  set_fact:
    haproxy_regex_key_val: "[a-zA-Z]+(?:=[^:;]+)?"
    haproxy_regex_key_vals: "(?:[a-zA-Z]+(?:=[^:;]+)?(?:;[a-zA-Z]+(?:=[^:;]+)?)*:)?"
    haproxy_regex_host_port: "(?:[^:@\\[\\]]+|\\[[0-9a-fA-F:]+\\]):\\d+"
    haproxy_regex_ipv6_host_port: "(?:[0-9a-fA-F:]+):{1,3}\\d+"
    haproxy_regex_port: "\\d+"
    haproxy_regex_weight: "(?:@\\d+)?"
    haproxy_regex_shared_config: "(?:[a-zA-Z]+(?:=[^:;]+)?(?:;[a-zA-Z]+(?:=[^:;]+)?)*\\s*\\|\\s*)?"
    haproxy_regex_frontend: "^([a-z0-9]+:)?([^\\s:]+)(:[\\d]+)\\s*->\\s*(.+)$"
    haproxy_regex_ipv4_host_port: "(?:[^:\\[\\]]+):\\d+"
    haproxy_regex_target: "([^\\s\\(]+)(?:\\s*\\((?:\\d+)\\))?"
    haproxy_regex_targets: "([^\\s\\(]+(?:\\s*\\(\\d+\\))?(?:\\s*,\\s*[^\\s\\(]+(?:\\s*\\(\\d+\\))?)*)$"

- name: Parse haproxy rules
  ansible.builtin.set_fact:
    parsed_rules: "{{ pfsense.haproxy.rules | default([]) }}"
    haproxy_rules: "{{ pfsense.haproxy.rules | default([]) }}"

- name: Normalize ipv6 addresses in haproxy rules
  ansible.builtin.set_fact:
    normalized_rules: |-
      {% set result = [] %}
      {% for rule in parsed_rules %}
        {% set rule_parts = rule | regex_findall('(?:[^:@\[\]]+|\[[0-9a-fA-F:]+\]):\d+') %}
        {% if rule_parts | length > 0 %}
          {% set _ = result.append(rule) %}
        {% endif %}
      {% endfor %}
      {{ result }}

- name: Parse haproxy rules
  ansible.builtin.set_fact:
    parsed_rules: |-
      {% set result = [] %}
      {% for rule in normalized_rules %}
        {% set _ = result.append(rule) %}
      {% endfor %}
      {{ result }}

- name: Set haproxy regex patterns
  ansible.builtin.set_fact:
    haproxy_regex_frontend: "^([a-z0-9]+:)?([^\\s:]+)(:[\\\\d]+)\\s*->\\s*(.+)$"
    haproxy_regex_ipv4_host_port: "(?:[^:\\[\\]]+):\\d+"
    haproxy_regex_ipv6_host_port: "(?:\\[[0-9a-fA-F:]+\\]:\\d+|[0-9a-fA-F:]+:{1,3}\\d+)"
    haproxy_regex_target: "([^\\s\\(]+)(?:\\s*\\((?:\\d+)\\))?"
    haproxy_regex_targets: "([^\\s\\(]+(?:\\s*\\(\\d+\\))?(?:\\s*,\\s*[^\\s\\(]+(?:\\s*\\(\\d+\\))?)*)$"

- name: Parse haproxy rules
  ansible.builtin.set_fact:
    parsed_rules: "{{ pfsense.haproxy.rules | default([]) }}"

- name: Configure haproxy settings
  ansible.builtin.include_tasks: settings.yml
  when: primary
- name: Configure ips
  include_tasks: ips.yml
- name: Configure haproxy
  include_tasks: haproxy.yml
