#!/bin/sh

if [ "$SSH_PUBLIC_KEYS_B64" = "" ]; then
    SSH_PUBLIC_KEYS_B64="$(cat $HOME/.ssh/id_rsa.pub | base64 -w0)"
fi
if [ "$EMAIL" = "" ] && [ "$CLOUDFLARE_EMAIL" != "" ]; then
    EMAIL="$CLOUDFLARE_EMAIL"
fi

export TF_VAR_app_dir="$APPS_DIR/$APP"
export TF_VAR_argocd="$ARGOCD"
export TF_VAR_ceph="$CEPH"
export TF_VAR_ceph_admin_id="$CEPH_ADMIN_ID"
export TF_VAR_ceph_admin_key="$CEPH_ADMIN_KEY"
export TF_VAR_ceph_cluster_id="$CEPH_CLUSTER_ID"
export TF_VAR_ceph_fs_name="$CEPH_FS_NAME"
export TF_VAR_ceph_monitors="$CEPH_MONITORS"
export TF_VAR_ceph_rbd_pool="$CEPH_RBD_POOL"
export TF_VAR_cloudflare_api_key="$CLOUDFLARE_API_KEY"
export TF_VAR_cloudflare_email="$CLOUDFLARE_EMAIL"
export TF_VAR_cluster_domain="$CLUSTER_DOMAIN"
export TF_VAR_cluster_entrypoint="$CLUSTER_ENTRYPOINT"
export TF_VAR_cluster_issuer="$CLUSTER_ISSUER"
export TF_VAR_dualstack="$DUALSTACK"
export TF_VAR_email="$EMAIL"
export TF_VAR_external_dns="$EXTERNAL_DNS"
export TF_VAR_flux="$FLUX"
export TF_VAR_gitlab_hostname="$GITLAB_HOSTNAME"
export TF_VAR_gitlab_repo="$GITLAB_REPO"
export TF_VAR_gitlab_token="$GITLAB_TOKEN"
export TF_VAR_gitlab_username="$GITLAB_USERNAME"
export TF_VAR_hetzner_api_key="$HETZNER_API_KEY"
export TF_VAR_ingress_nginx="$INGRESS_NGINX"
export TF_VAR_ingress_ports="$INGRESS_PORTS"
export TF_VAR_integration_operator="$INTEGRATION_OPERATOR"
export TF_VAR_ip_range="$IP_RANGE"
export TF_VAR_iteration="$ITERATION"
export TF_VAR_kanister="$KANISTER"
export TF_VAR_kanister_bucket="$KANISTER_BUCKET"
export TF_VAR_kube_network_plugin="$KUBE_NETWORK_PLUGIN"
export TF_VAR_kube_version="$KUBE_VERSION"
export TF_VAR_kyverno="$KYVERNO"
export TF_VAR_longhorn="$LONGHORN"
export TF_VAR_olm="$OLM"
export TF_VAR_prefix="$APP"
export TF_VAR_protection="$PROTECTION"
export TF_VAR_rancher="$RANCHER"
export TF_VAR_rancher_hostname="$RANCHER_HOSTNAME"
export TF_VAR_rancher_istio="$RANCHER_ISTIO"
export TF_VAR_rancher_logging="$RANCHER_LOGGING"
export TF_VAR_rancher_monitoring="$RANCHER_MONITORING"
export TF_VAR_rancher_token="$RANCHER_TOKEN"
export TF_VAR_reloader="$RELOADER"
export TF_VAR_s3="$S3"
export TF_VAR_s3_access_key="$S3_ACCESS_KEY"
export TF_VAR_s3_endpoint="$S3_ENDPOINT"
export TF_VAR_s3_secret_key="$S3_SECRET_KEY"
export TF_VAR_single_control_plane="$SINGLE_CONTROL_PLANE"
export TF_VAR_ssh_public_keys_b64="$SSH_PUBLIC_KEYS_B64"
export TF_VAR_user="$USER"
export TF_VAR_vault="$VAULT"
if [ "$MASTER_IPS" != "" ]; then
    export TF_VAR_master_ips="$(echo "$MASTER_IPS" | jq -R 'split(" ")')"
fi
if [ "$WORKER_IPS" != "" ]; then
    export TF_VAR_worker_ips="$(echo "$WORKER_IPS" | jq -R 'split(" ")')"
fi
