services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "${S3_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${S3_SECRET_KEY}"
    command: minio gateway s3 "${S3_ENDPOINT}"
