---
- name: Check dhcp configuration
  ansible.builtin.shell: |
    cat <<EOF > /tmp/check_dhcp.php
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    $network_parts = explode('/', '{{ item.value.ipv4.primary }}');
    $ip_parts = explode('.', $network_parts[0]);
    $ipv6_parts = explode('/', '{{ item.value.ipv6.primary }}');
    $ipv6_prefix = explode('::', $ipv6_parts[0])[0];
    $interface = '{{ item.key }}';
    $current = array(
      'dhcpbackend' => config_get_path('dhcpbackend', 'isc'),
      'dhcpd' => array(
        $interface => array(
          'enable' => isset($config['dhcpd'][$interface]['enable']) ? 'yes' : '',
          'range' => array(
            'from' => config_get_path('dhcpd/' . $interface . '/range/from', ''),
            'to' => config_get_path('dhcpd/' . $interface . '/range/to', '')
          )
        )
      ),
      'dhcpdv6' => array(
        $interface => array(
          'enable' => isset($config['dhcpdv6'][$interface]['enable']) ? 'yes' : '',
          'range' => array(
            'from' => config_get_path('dhcpdv6/' . $interface . '/range/from', ''),
            'to' => config_get_path('dhcpdv6/' . $interface . '/range/to', '')
          ),
          'ramode' => config_get_path('dhcpdv6/' . $interface . '/ramode', 'assist')
        )
      )
    );
    $desired = array(
      'dhcpbackend' => 'kea',
      'dhcpd' => array(
        $interface => array(
          'enable' => {{ item.value.dhcp | default(false) | bool | to_json }} ? 'yes' : '',
          'range' => array(
            'from' => $ip_parts[0] . '.' . $ip_parts[1] . '.0.1',
            'to' => $ip_parts[0] . '.' . $ip_parts[1] . '.255.254'
          )
        )
      ),
      'dhcpdv6' => array(
        $interface => array(
          'enable' => '',
          'range' => array(
            'from' => $ipv6_prefix . '::',
            'to' => $ipv6_prefix . '::ffff:ffff:ffff:ffff'
          ),
          'ramode' => 'unmanaged'
        )
      )
    );
    echo json_encode(array(
      'changed' => $current != $desired,
      'current' => $current,
      'desired' => $desired
    ));
    EOF
    php -f /tmp/check_dhcp.php
    rm -f /tmp/check_dhcp.php
  loop: "{{ pfsense.network.interfaces | dict2items }}"
  when:
    - pfsense.network.interfaces is defined
    - item.key != 'wan'
  register: dhcp_check
  changed_when: (dhcp_check.stdout | from_json).changed

- name: Configure dhcp
  ansible.builtin.shell: |-
    cat <<EOF > /tmp/update_dhcp.php
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    require_once("system.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    config_set_path('dhcpbackend', 'kea');
    $network_parts = explode('/', '{{ item.0.value.ipv4.primary }}');
    $ip_parts = explode('.', $network_parts[0]);
    $interface = '{{ item.0.key }}';
    config_set_path('dhcpd/' . $interface . '/range/from', $ip_parts[0] . '.' . $ip_parts[1] . '.0.1');
    config_set_path('dhcpd/' . $interface . '/range/to', $ip_parts[0] . '.' . $ip_parts[1] . '.255.254');
    $ipv6_parts = explode('/', '{{ item.0.value.ipv6.primary }}');
    $ipv6_prefix = explode('::', $ipv6_parts[0])[0];
    if ({{ item.0.value.dhcp | default(false) | bool | to_json }}) {
        config_set_path('dhcpd/' . $interface . '/enable', 'yes');
    } else {
        if (isset($config['dhcpd'][$interface]['enable'])) {
            unset($config['dhcpd'][$interface]['enable']);
        }
        config_del_path('dhcpd/' . $interface . '/enable');
    }
    if (isset($config['dhcpdv6'][$interface]['enable'])) {
        unset($config['dhcpdv6'][$interface]['enable']);
    }
    config_del_path('dhcpdv6/' . $interface . '/enable');
    config_set_path('dhcpdv6/' . $interface . '/range/from', $ipv6_prefix . '::');
    config_set_path('dhcpdv6/' . $interface . '/range/to', $ipv6_prefix . '::ffff:ffff:ffff:ffff');
    config_set_path('dhcpdv6/' . $interface . '/ramode', 'unmanaged');
    config_set_path('dhcpdv6/' . $interface . '/rapriority', 'medium');
    if (write_config(sprintf('Updated dhcp configuration from ansible (%s@%s)', '{{ ansible_user }}', '{{ ansible_host }}'))) {
        services_dhcpd_configure();
    }
    EOF
    {% if item.1 is changed %}
    php -f /tmp/update_dhcp.php
    {% endif %}
    rm -f /tmp/update_dhcp.php
  loop: "{{ pfsense.network.interfaces | dict2items | zip(dhcp_check.results) | list }}"
  when:
    - pfsense.network.interfaces is defined
    - item.0.key != 'wan'
  changed_when: item.1 is changed
