---
- name: Validate lan interface exists
  ansible.builtin.assert:
    that:
      - pfsense.network.interfaces is defined
      - pfsense.network.interfaces.lan is defined
    fail_msg: "A lan interface is required"

- name: Validate interface ip configurations
  ansible.builtin.assert:
    that:
      - |
        (item.value.ipv4 is string) or
        (item.value.ipv4.primary is string and item.value.ipv4.secondary is string)
      - |
        ((item.value.ipv4 is string and item.value.ipv4 | regex_search('^[0-9.]+/[0-9]+$')) or
        (item.value.ipv4.primary | regex_search('^[0-9.]+/[0-9]+$') and
         item.value.ipv4.secondary | regex_search('^[0-9.]+/[0-9]+$')))
      - |
        not item.value.ipv6 is defined or
        (item.value.ipv6.primary | regex_search('^[0-9a-fA-F:]+/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8])$') and
         item.value.ipv6.secondary | regex_search('^[0-9a-fA-F:]+/([0-9]|[1-9][0-9]|1[0-1][0-9]|12[0-8])$'))
    fail_msg: "Invalid ip for interface {{ item.key }}"
  loop: "{{ pfsense.network.interfaces | dict2items }}"
  when:
    - pfsense.network.interfaces is defined
    - item.key != 'wan'

- name: Check current interface configuration
  ansible.builtin.shell: |
    cat > /tmp/check_interface.php << 'EOF'
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    $interface = $argv[1];
    $ipv4 = $argv[2];
    $prefixlen = $argv[3];
    $ipv6 = isset($argv[4]) ? $argv[4] : null;
    $prefixlen6 = isset($argv[5]) ? $argv[5] : null;
    $current = array(
      'ipaddr' => config_get_path('interfaces/' . $interface . '/ipaddr', ''),
      'subnet' => config_get_path('interfaces/' . $interface . '/subnet', ''),
      'ipaddrv6' => config_get_path('interfaces/' . $interface . '/ipaddrv6', null),
      'subnetv6' => config_get_path('interfaces/' . $interface . '/subnetv6', null),
      'if' => config_get_path('interfaces/' . $interface . '/if', ''),
      'enable' => isset($config['interfaces'][$interface]['enable']),
      'ipaddr_dhcp' => isset($config['interfaces'][$interface]['ipaddr']) && $config['interfaces'][$interface]['ipaddr'] === 'dhcp'
    );
    $desired = array(
      'ipaddr' => {% if item.value.dhcp | default(false) %}$ipv4{% else %}'dhcp'{% endif %},
      'subnet' => {% if item.value.dhcp | default(false) %}$prefixlen{% else %}''{% endif %},
      'ipaddrv6' => $ipv6,
      'subnetv6' => $prefixlen6,
      'if' => "{{ item.value.interface }}",
      'enable' => true,
      'ipaddr_dhcp' => {% if item.value.dhcp | default(false) %}false{% else %}true{% endif %}
    );
    echo json_encode(array(
      'changed' => $current != $desired,
      'current' => $current,
      'desired' => $desired
    ));
    EOF
    interface="{{ item.key }}"
    ipv4="{{ primary | ternary(item.value.ipv4.primary | regex_replace('/.*$', ''), item.value.ipv4.secondary | regex_replace('/.*$', '')) }}"
    prefixlen="{{ primary | ternary(item.value.ipv4.primary | regex_replace('^.*/', ''), item.value.ipv4.secondary | regex_replace('^.*/', '')) }}"
    {% if item.value.ipv6 is defined %}
    ipv6="{{ primary | ternary(item.value.ipv6.primary | regex_replace('/.*$', ''), item.value.ipv6.secondary | regex_replace('/.*$', '')) }}"
    prefixlen6="{{ primary | ternary(item.value.ipv6.primary | regex_replace('^.*/', ''), item.value.ipv6.secondary | regex_replace('^.*/', '')) }}"
    php -f /tmp/check_interface.php "$interface" "$ipv4" "$prefixlen" "$ipv6" "$prefixlen6"
    {% else %}
    php -f /tmp/check_interface.php "$interface" "$ipv4" "$prefixlen"
    {% endif %}
    rm -f /tmp/check_interface.php
  loop: "{{ pfsense.network.interfaces | dict2items }}"
  when:
    - pfsense.network.interfaces is defined
    - item.key != 'wan'
  register: interface_check
  changed_when: (interface_check.stdout | from_json).changed

- name: Configure interfaces
  ansible.builtin.shell: |
    cat > /tmp/update_interface.php << 'EOF'
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    require_once("interfaces.inc");
    require_once("gwlb.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    $interface = $argv[1];
    $ipv4 = $argv[2];
    $prefixlen = $argv[3];
    $ipv6 = isset($argv[4]) ? $argv[4] : null;
    $prefixlen6 = isset($argv[5]) ? $argv[5] : null;
    config_set_path('interfaces/' . $interface . '/enable', true);
    config_set_path('interfaces/' . $interface . '/if', "{{ item.0.value.interface }}");
    {% if item.0.value.dhcp | default(false) %}
    config_set_path('interfaces/' . $interface . '/ipaddr', $ipv4);
    config_set_path('interfaces/' . $interface . '/subnet', $prefixlen);
    {% else %}
    config_set_path('interfaces/' . $interface . '/ipaddr', 'dhcp');
    if (isset($config['interfaces'][$interface]['subnet'])) {
        unset($config['interfaces'][$interface]['subnet']);
    }
    {% endif %}
    if ($ipv6 !== null) {
        config_set_path('interfaces/' . $interface . '/ipaddrv6', $ipv6);
        config_set_path('interfaces/' . $interface . '/subnetv6', $prefixlen6);
        config_set_path('interfaces/' . $interface . '/ipv6_enable', true);
        config_set_path('interfaces/' . $interface . '/ipv6_mode', 'static');
        config_set_path('interfaces/' . $interface . '/dhcp6client', false);
    } else {
        config_set_path('interfaces/' . $interface . '/ipv6_enable', false);
    }
    write_config(sprintf('Updated interface configuration from ansible (%s@%s)', '{{ ansible_user }}', '{{ ansible_host }}'));
    interface_configure($interface);
    filter_configure();
    EOF
    {% if item.1 is changed %}
    interface="{{ item.0.key }}"
    ipv4="{{ primary | ternary(item.0.value.ipv4.primary | regex_replace('/.*$', ''), item.0.value.ipv4.secondary | regex_replace('/.*$', '')) }}"
    prefixlen="{{ primary | ternary(item.0.value.ipv4.primary | regex_replace('^.*/', ''), item.0.value.ipv4.secondary | regex_replace('^.*/', '')) }}"
    {% if item.0.value.ipv6 is defined %}
    ipv6="{{ primary | ternary(item.0.value.ipv6.primary | regex_replace('/.*$', ''), item.0.value.ipv6.secondary | regex_replace('/.*$', '')) }}"
    prefixlen6="{{ primary | ternary(item.0.value.ipv6.primary | regex_replace('^.*/', ''), item.0.value.ipv6.secondary | regex_replace('^.*/', '')) }}"
    php -f /tmp/update_interface.php "$interface" "$ipv4" "$prefixlen" "$ipv6" "$prefixlen6"
    {% else %}
    php -f /tmp/update_interface.php "$interface" "$ipv4" "$prefixlen"
    {% endif %}
    {% endif %}
    rm -f /tmp/update_interface.php
  loop: "{{ pfsense.network.interfaces | dict2items | zip(interface_check.results) | list }}"
  when:
    - pfsense.network.interfaces is defined
    - item.0.key != 'wan'
  changed_when: item.1 is changed
