---
- name: Configure interfaces
  import_tasks: interfaces.yml
- name: Configure setup
  import_tasks: setup.yml
- name: Configure sync
  import_tasks: sync.yml
- name: Configure dashboard
  import_tasks: dashboard.yml
- name: Configure dhcp
  import_tasks: dhcp.yml
# - name: Configure NAT
#   import_tasks: nat.yml
# - name: Configure firewall rules
#   import_tasks: firewall.yml
# - name: Install and configure packages
#   import_tasks: packages.yml
