---
- name: Check nat configuration
  ansible.builtin.shell: |
    cat > /tmp/check_nat.php << 'EOF'
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    function normalize_bool($value) {
        if ($value === "" || $value === true) {
            return true;
        }
        return $value;
    }
    function normalize_rule($rule) {
        if (isset($rule['destination']['any'])) {
            $rule['destination']['any'] = normalize_bool($rule['destination']['any']);
        }
        if (isset($rule['nordr'])) {
            $rule['nordr'] = normalize_bool($rule['nordr']);
        }
        return $rule;
    }
    $current = array(
      'nat' => array(
        'outbound' => array(
          'mode' => isset($config['nat']['outbound']['mode']) ? $config['nat']['outbound']['mode'] : '',
          'rule' => array()
        )
      )
    );
    if (isset($config['nat']['outbound']['rule'])) {
        foreach ($config['nat']['outbound']['rule'] as $rule) {
            $current['nat']['outbound']['rule'][] = normalize_rule($rule);
        }
    }
    $desired = array(
      'nat' => array(
        'outbound' => array(
          'mode' => 'hybrid',
          'rule' => array(
            normalize_rule(array(
              'interface' => 'wan',
              'source' => array(
                'network' => '{{ pfsense.network.interfaces.lan.subnet }}'
              ),
              'destination' => array(
                'any' => true
              ),
              'target' => '',
              'ipprotocol' => 'inet46',
              'nordr' => true
            ))
          )
        )
      )
    );
    echo json_encode(array(
      'changed' => $current != $desired,
      'current' => $current,
      'desired' => $desired
    ));
    EOF
    php -f /tmp/check_nat.php
    rm -f /tmp/check_nat.php
  register: nat_check
  changed_when: (nat_check.stdout | from_json).changed
  when: primary

- name: Configure nat
  ansible.builtin.shell: |
    cat > /tmp/update_nat.php << 'EOF'
    <?php
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    require_once("interfaces.inc");
    global $config;
    if (!is_array($config)) {
        $config = parse_config();
    }
    if (!isset($config['nat'])) {
        $config['nat'] = array();
    }
    if (!isset($config['nat']['outbound'])) {
        $config['nat']['outbound'] = array();
    }
    $config['nat']['outbound']['mode'] = 'hybrid';
    $config['nat']['outbound']['rule'] = array(
      array(
        'interface' => 'wan',
        'source' => array(
          'network' => '{{ pfsense.network.interfaces.lan.subnet }}'
        ),
        'destination' => array(
          'any' => true
        ),
        'target' => '',
        'ipprotocol' => 'inet46',
        'nordr' => true
      )
    );
    if (write_config(sprintf('Updated NAT configuration from ansible (%s@%s)', '{{ ansible_user }}', '{{ ansible_host }}'))) {
      filter_configure();
    }
    EOF
    {% if nat_check is changed %}
    php -f /tmp/update_nat.php
    {% endif %}
    rm -f /tmp/update_nat.php
  changed_when: nat_check is changed
  when: primary
