---
- name: Install haproxy
  package:
    name: pfSense-pkg-haproxy
    state: present

- name: Install acme
  package:
    name: pfSense-pkg-acme
    state: present
  when: primary

- name: Install pfBlockerNG
  package:
    name: pfSense-pkg-pfBlockerNG
    state: present
