---
- name: Check routes configuration
  ansible.builtin.shell: |-
    cat <<EOF > /tmp/check_routes.php
    <?php
    require_once("globals.inc");
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    require_once("interfaces.inc");
    require_once("gwlb.inc");
    global $config;
    $config = parse_config(true);
    $current = array(
      'staticroutes' => array(),
      'system' => array(
        'disablechecksumoffloading' => isset($config['system']['disablechecksumoffloading']) ? 'yes' : ''
      )
    );
    if (isset($config['staticroutes']['route']) && is_array($config['staticroutes']['route'])) {
      $current['staticroutes'] = $config['staticroutes']['route'];
    }
    $desired = array(
      'staticroutes' => array(),
      'system' => array(
        'disablechecksumoffloading' => 'yes'
      )
    );
    $network = '';
    $network_parts = explode('/', '{{ pfsense.network.interfaces.lan.ipv4.primary }}');
    $ip_parts = explode('.', $network_parts[0]);
    $network = $ip_parts[0] . '.' . $ip_parts[1] . '.0.0/' . $network_parts[1];
    $desired['staticroutes'] = array(
      array(
        'network' => $network,
        'gateway' => 'LAN_DHCP'
      )
    );
    echo json_encode(array(
      'changed' => $current != $desired,
      'current' => $current,
      'desired' => $desired
    ));
    EOF
    php -f /tmp/check_routes.php
    rm -f /tmp/check_routes.php
  register: routes_check
  changed_when: (routes_check.stdout | from_json).changed
  when:
    - pfsense.network.interfaces.lan is defined
    - not pfsense.network.interfaces.lan.dhcp | default(false)

- name: Configure routes
  ansible.builtin.shell: |-
    cat <<EOF > /tmp/update_routes.php
    <?php
    require_once("globals.inc");
    require_once("config.inc");
    require_once("util.inc");
    require_once("config.lib.inc");
    require_once("interfaces.inc");
    require_once("gwlb.inc");
    global $config;
    $config = parse_config(true);
    $network = '';
    $network_parts = explode('/', '{{ pfsense.network.interfaces.lan.ipv4.primary }}');
    $ip_parts = explode('.', $network_parts[0]);
    $network = $ip_parts[0] . '.' . $ip_parts[1] . '.0.0/' . $network_parts[1];
    if (!isset($config['staticroutes']) || !is_array($config['staticroutes'])) {
      $config['staticroutes'] = array();
    }
    $config['staticroutes']['route'] = array(
      array(
        'network' => $network,
        'gateway' => 'LAN_DHCP'
      )
    );
    config_set_path('system/disablechecksumoffloading', true);
    if (write_config(sprintf('Updated routes configuration from ansible (%s@%s)', '{{ ansible_user }}', '{{ ansible_host }}'))) {
      mark_subsystem_dirty('staticroutes');
      system_routing_configure();
      filter_configure();
      clear_subsystem_dirty('staticroutes');
    }
    EOF
    {% if routes_check is changed %}
    php -f /tmp/update_routes.php
    {% endif %}
    rm -f /tmp/update_routes.php
  changed_when: routes_check is changed
  when:
    - pfsense.network.interfaces.lan is defined
    - not pfsense.network.interfaces.lan.dhcp | default(false)
