---
- name: Upgrade All Packages To The Latest Version
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install Core Dependencies, Clean APT, & Remove Old Programs
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: true
    autoremove: true
    autoclean: true
  loop:
    - apt-transport-https
    - ca-certificates
    - cloud-init
    - curl
    - gnupg-agent
    - htop
    - linux-headers-amd64
    - linux-image-amd64
    - ncdu
    - software-properties-common
    - sudo
    - tmux
    - unattended-upgrades
    - wget
