---
- name: Add GPG key for Docker Repository
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present
    filename: docker

- name: Install Docker Engine, Docker CLI, Containerd, & Docker Compose
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
    install_recommends: true
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin

- name: Set Docker Registry Proxy Configuration
  ansible.builtin.copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "metrics-addr": "127.0.0.1:9323",
        "experimental": true
      }
