---
- hosts: all
  gather_facts: false
  tasks:
    - name: Check if post-install script exists
      ansible.builtin.stat:
        path: /tmp/postinstall.sh
      register: script_file
      changed_when: false
    - name: Execute post-install tasks
      when: script_file.stat.exists
      block:
        - name: Execute post-install script
          ansible.builtin.command: /tmp/postinstall.sh
          register: script_output
        - name: Display script output
          ansible.builtin.debug:
            var: script_output.stdout_lines
        - name: Remove temporary script file
          ansible.builtin.file:
            path: /tmp/postinstall.sh
            state: absent
          register: remove_result
